//go:build integration
// +build integration

package controllers

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/tools/events"
	"k8s.io/utils/ptr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/envtest"

	v1alpha1 "sigs.k8s.io/agent-sandbox/api/v1alpha1"
	sandboxcontrollers "sigs.k8s.io/agent-sandbox/controllers"
	extensionsv1alpha1 "sigs.k8s.io/agent-sandbox/extensions/api/v1alpha1"
	asmetrics "sigs.k8s.io/agent-sandbox/internal/metrics"
)

func TestSandboxClaimNoReAdoptionIntegration(t *testing.T) {
	// 1. Setup EnvTest
	crdPath := filepath.Join("..", "..", "k8s", "crds")

	testEnv := &envtest.Environment{
		CRDDirectoryPaths: []string{crdPath},
	}

	cfg, err := testEnv.Start()
	if err != nil {
		t.Fatalf("Failed to start test environment: %v", err)
	}
	defer testEnv.Stop()

	// 2. Setup Scheme
	scheme := runtime.NewScheme()
	_ = corev1.AddToScheme(scheme)
	_ = v1alpha1.AddToScheme(scheme)
	_ = extensionsv1alpha1.AddToScheme(scheme)

	// 3. Create Direct Client (to setup state before controller starts)
	k8sClient, err := client.New(cfg, client.Options{Scheme: scheme})
	if err != nil {
		t.Fatalf("Failed to create client: %v", err)
	}

	ctx := context.Background()

	// 4. Setup State
	ns := &corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: "test-ns"}}
	if err := k8sClient.Create(ctx, ns); err != nil {
		t.Fatalf("Failed to create namespace: %v", err)
	}

	template := &extensionsv1alpha1.SandboxTemplate{
		ObjectMeta: metav1.ObjectMeta{Name: "test-template", Namespace: "test-ns"},
		Spec: extensionsv1alpha1.SandboxTemplateSpec{
			PodTemplate: v1alpha1.PodTemplate{
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{{Name: "c", Image: "img"}},
				},
			},
		},
	}
	if err := k8sClient.Create(ctx, template); err != nil {
		t.Fatalf("Failed to create template: %v", err)
	}

	claim := &extensionsv1alpha1.SandboxClaim{
		ObjectMeta: metav1.ObjectMeta{Name: "test-claim", Namespace: "test-ns"},
		Spec:       extensionsv1alpha1.SandboxClaimSpec{TemplateRef: extensionsv1alpha1.SandboxTemplateRef{Name: "test-template"}},
	}
	if err := k8sClient.Create(ctx, claim); err != nil {
		t.Fatalf("Failed to create claim: %v", err)
	}

	// Get the real UID generated by the API server
	claimUID := claim.UID
	if claimUID == "" {
		t.Fatal("Claim UID is empty after creation")
	}

	// Create a sandbox that appears ALREADY ADOPTED by the claim (labeled and owned)
	adoptedSandbox := &v1alpha1.Sandbox{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "adopted-sb",
			Namespace: "test-ns",
			Labels: map[string]string{
				extensionsv1alpha1.SandboxIDLabel: string(claimUID),
			},
			OwnerReferences: []metav1.OwnerReference{{
				APIVersion: "extensions.agents.x-k8s.io/v1alpha1",
				Kind:       "SandboxClaim",
				Name:       "test-claim",
				UID:        claimUID,
				Controller: ptr.To(true),
			}},
		},
		Spec: v1alpha1.SandboxSpec{
			Replicas:    ptr.To(int32(1)),
			PodTemplate: v1alpha1.PodTemplate{Spec: corev1.PodSpec{Containers: []corev1.Container{{Name: "c", Image: "img"}}}},
		},
	}
	if err := k8sClient.Create(ctx, adoptedSandbox); err != nil {
		t.Fatalf("Failed to create adopted sandbox: %v", err)
	}

	// Create another sandbox in the warm pool that should NOT be adopted
	poolNameHash := sandboxcontrollers.NameHash("test-pool")
	poolSandbox := &v1alpha1.Sandbox{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "pool-sb-extra",
			Namespace: "test-ns",
			Labels: map[string]string{
				warmPoolSandboxLabel:   poolNameHash,
				sandboxTemplateRefHash: sandboxcontrollers.NameHash("test-template"),
			},
		},
		Spec: v1alpha1.SandboxSpec{
			Replicas:    ptr.To(int32(1)),
			PodTemplate: v1alpha1.PodTemplate{Spec: corev1.PodSpec{Containers: []corev1.Container{{Name: "c", Image: "img"}}}},
		},
		Status: v1alpha1.SandboxStatus{
			Conditions: []metav1.Condition{{
				Type:   string(v1alpha1.SandboxConditionReady),
				Status: metav1.ConditionTrue,
				Reason: "Ready",
			}},
		},
	}
	if err := k8sClient.Create(ctx, poolSandbox); err != nil {
		t.Fatalf("Failed to create pool sandbox: %v", err)
	}

	// 5. Setup Manager and Start Controller
	mgr, err := ctrl.NewManager(cfg, ctrl.Options{Scheme: scheme})
	if err != nil {
		t.Fatalf("Failed to create manager: %v", err)
	}

	// Index Sandboxes by Claim UID label for fast lookup
	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &v1alpha1.Sandbox{}, "idx.claim-uid", func(rawObj client.Object) []string {
		sb := rawObj.(*v1alpha1.Sandbox)
		if sb.Labels == nil {
			return nil
		}
		if val, ok := sb.Labels[extensionsv1alpha1.SandboxIDLabel]; ok {
			return []string{val}
		}
		return nil
	}); err != nil {
		t.Fatalf("Failed to create index: %v", err)
	}

	// Index Sandboxes by Template Hash label for fast lookup
	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &v1alpha1.Sandbox{}, "idx.template-hash", func(rawObj client.Object) []string {
		sb := rawObj.(*v1alpha1.Sandbox)
		if sb.Labels == nil {
			return nil
		}
		if val, ok := sb.Labels["agents.x-k8s.io/sandbox-template-ref-hash"]; ok {
			return []string{val}
		}
		return nil
	}); err != nil {
		t.Fatalf("Failed to create index: %v", err)
	}

	// Register Controller
	reconciler := &SandboxClaimReconciler{
		Client:           mgr.GetClient(),
		Scheme:           mgr.GetScheme(),
		Recorder:         events.NewFakeRecorder(10),
		Tracer:           asmetrics.NewNoOp(),
	}
	if err := reconciler.SetupWithManager(mgr, 1); err != nil {
		t.Fatalf("Failed to setup controller: %v", err)
	}

	// Start Manager
	cancelCtx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go func() {
		if err := mgr.Start(cancelCtx); err != nil {
			t.Errorf("Manager failed: %v", err)
		}
	}()

	// 6. Wait and Verify
	// Wait for the controller to reconcile the claim.
	// Since we already have an owned sandbox, it should NOT adopt the pool sandbox.
	time.Sleep(5 * time.Second) // Give it enough time to reconcile

	// Verify the pool sandbox still has warm pool labels (was not adopted)
	var extra v1alpha1.Sandbox
	if err := k8sClient.Get(ctx, types.NamespacedName{Name: "pool-sb-extra", Namespace: "test-ns"}, &extra); err != nil {
		t.Fatalf("failed to get pool sandbox: %v", err)
	}
	if _, ok := extra.Labels[warmPoolSandboxLabel]; !ok {
		t.Error("pool sandbox should still have warm pool label (should not have been adopted)")
	}

	// Verify the claim status is updated with the ALREADY OWNED sandbox name
	var updatedClaim extensionsv1alpha1.SandboxClaim
	if err := k8sClient.Get(ctx, types.NamespacedName{Name: "test-claim", Namespace: "test-ns"}, &updatedClaim); err != nil {
		t.Fatalf("failed to get updated claim: %v", err)
	}
	if updatedClaim.Status.SandboxStatus.Name != "adopted-sb" {
		t.Errorf("expected claim status to reference 'adopted-sb', got %q", updatedClaim.Status.SandboxStatus.Name)
	}
}
